global:
  scrape_interval: 5s
  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter:9100"]
